x-generator: NSwag v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: My Title
  version: 1.0.0
paths:
  /api/Tags:
    get:
      tags:
      - Tags
      operationId: Tags_GetTags
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
    post:
      tags:
      - Tags
      operationId: Tags_PostTag
      requestBody:
        x-name: tag
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
  /api/Tags/{id}:
    get:
      tags:
      - Tags
      summary: Get Tag by Id
      operationId: Tags_GetTag
      parameters:
      - name: id
        in: path
        required: true
        description: The tags Id
        schema:
          type: integer
          format: int32
        x-position: 1
      responses:
        404:
          description: fghfghf
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
    put:
      tags:
      - Tags
      operationId: Tags_PutTag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
        x-position: 1
      requestBody:
        x-name: tag
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tag'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
    delete:
      tags:
      - Tags
      operationId: Tags_DeleteTag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
  /api/Places:
    get:
      tags:
      - Places
      operationId: Places_GetPlaces
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Place'
    post:
      tags:
      - Places
      operationId: Places_PostPlace
      requestBody:
        x-name: place
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Place'
        required: true
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
  /api/Places/{id}:
    get:
      tags:
      - Places
      operationId: Places_GetPlace
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Place'
    put:
      tags:
      - Places
      operationId: Places_PutPlace
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
        x-position: 1
      requestBody:
        x-name: place
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Place'
        required: true
        x-position: 2
      responses:
        200:
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
    delete:
      tags:
      - Places
      operationId: Places_DeletePlace
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int32
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
components:
  schemas:
    Tag:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
    ProblemDetails:
      type: object
      additionalProperties:
        nullable: true
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
    Place:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        address:
          $ref: '#/components/schemas/Address'
        contactInformation:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ContactInformation'
    Address:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
        street:
          type: string
        city:
          type: string
        number:
          type: string
        postalCode:
          type: string
        country:
          type: string
    ContactInformation:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
        description:
          type: string
        value:
          type: string
