namespace LunchFinder.Server.Places;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

/// <summary>
///     Represents a place where you can get Lunch
/// </summary>
public class Place
{
    /// <summary>
    ///     ID generated by the database
    /// </summary>
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    ///     Name of the place
    /// </summary>
    [MaxLength(450)]
    public required string Name { get; set; }

    /// <summary>
    ///     Description of the place
    /// </summary>
    [MaxLength(4000)]
    public required string Description { get; set; }

    /// <summary>
    ///     List of tags attached to the place
    /// </summary>
    public required List<Tag> Tags { get; set; }

    /// <summary>
    ///     Address of the place
    /// </summary>
    public required Address Address { get; set; }


    /// <summary>
    ///     A list of contact information for the place
    /// </summary>
    public List<ContactInformation>? ContactInformation { get; set; }
}

/// <summary>
///     Represents an address
/// </summary>
public class Address
{
    /// <summary>
    ///     ID generated by the database
    /// </summary>
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    ///     Name of the street
    /// </summary>
    [MaxLength(200)]
    public required string Street { get; set; }


    /// <summary>
    ///     Name of the city
    /// </summary>
    [MaxLength(200)]
    public required string City { get; set; }


    /// <summary>
    ///     House number
    /// </summary>
    [MaxLength(200)]
    public required string Number { get; set; }


    /// <summary>
    ///     Postal code
    /// </summary>
    [MaxLength(200)]
    public required string PostalCode { get; set; }


    /// <summary>
    ///     Name of the country
    /// </summary>
    [MaxLength(200)]
    public required string Country { get; set; }
}

/// <summary>
///     Represents contact information
/// </summary>
public class ContactInformation
{
    /// <summary>
    ///     ID generated by the database
    /// </summary>
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    ///     Description of the place
    /// </summary>
    [MaxLength(500)]
    public required string Description { get; set; }

    /// <summary>
    ///     Description of the place
    /// </summary>
    [MaxLength(500)]
    public required string Value { get; set; }
}