namespace LunchFinder.Server.Tags;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;

/// <summary>
///     Represents a tag
/// </summary>
public class Tag
{
    /// <summary>
    ///     ID generated by the database
    /// </summary>
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    /// <summary>
    ///     Display name of the tag
    /// </summary>
    [MaxLength(50)]
    public required string Name { get; set; }

    /// <summary>
    ///     Description of the tag
    /// </summary>
    [MaxLength(500)]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    ///     The color the tag should be rendered in
    /// </summary>
    public required Color Color { get; set; } = Color.Blue;
}